# Generated by Django 3.2 on 2021-04-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('tracks', models.CharField(max_length=100)),
                ('self_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('albums', models.CharField(max_length=100)),
                ('tracks', models.CharField(max_length=100)),
                ('self_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('times_played', models.IntegerField()),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('self_url', models.CharField(max_length=100)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracionify.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracionify.artist'),
        ),
    ]
